{% set name = "finetuning-scheduler" %}
{% set version = "2.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/speediedan/finetuning-scheduler/releases/download/v{{ version }}/finetuning_scheduler-{{ version }}.tar.gz
  sha256: 900ed33fe795c6d18bbf38f21ed3abd357fe93b4b0ebd7a7b9ff5eb2c899c8d6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - wheel
  run:
    - python >=3.8
    - lightning >=2.2.0, <2.2.5
    - pytorch >=1.13.0

test:
  imports:
    - finetuning_scheduler
  requires:
    - pip

about:
  home: https://github.com/speediedan/finetuning-scheduler
  summary: A PyTorch Lightning extension that enhances model experimentation with flexible fine-tuning schedules.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://finetuning-scheduler.readthedocs.io/en/stable/
  dev_url: https://github.com/speediedan/finetuning-scheduler
  description: |
    The FinetuningScheduler callback accelerates and enhances foundational model experimentation with flexible fine-tuning
    schedules. Training with the FinetuningScheduler callback is simple and confers a host of benefits:

    - it dramatically increases fine-tuning flexibility
    - expedites and facilitates exploration of model tuning dynamics
    - enables marginal performance improvements of finetuned models

    Fundamentally, the FinetuningScheduler callback enables multi-phase, scheduled fine-tuning of foundational models.
    Gradual unfreezing (i.e. thawing) can help maximize foundational model knowledge retention while allowing (typically
    upper layers of) the model to optimally adapt to new tasks during transfer learning.

    FinetuningScheduler orchestrates the gradual unfreezing of models via a fine-tuning schedule that is either implicitly
    generated (the default) or explicitly provided by the user (more computationally efficient). Fine-tuning phase
    transitions are driven by FTSEarlyStopping criteria (a multi-phase extension of EarlyStopping), user-specified epoch
    transitions or a composition of the two (the default mode). A FinetuningScheduler training session completes when the
    final phase of the schedule has its stopping criteria met.

    Documentation
    -------------
    - https://finetuning-scheduler.readthedocs.io/en/stable/
    - https://finetuning-scheduler.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - speediedan
