{% set name = "finetuning-scheduler" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/finetuning-scheduler-{{ version }}.tar.gz
  sha256: 174577cab0e7fa5a2edfa96cd9a2b608c5160157f57352f8672a0f7a70d167dc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - pytorch-lightning >=1.6.0, <=1.6.2
    - setuptools <59.6
    - pytorch >=1.8

test:
  imports:
    - finetuning_scheduler
  requires:
    - pip

about:
  home: https://github.com/speediedan/finetuning-scheduler
  summary: A PyTorch Lightning extension that enhances model experimentation with flexible finetuning schedules.
  license: Apache-2.0
  license_file: LICENSE
  description: |
    The FinetuningScheduler callback accelerates and enhances foundational model experimentation with flexible finetuning
    schedules. Training with the FinetuningScheduler callback is simple and confers a host of benefits:

    - it dramatically increases finetuning flexibility
    - expedites and facilitates exploration of model tuning dynamics
    - enables marginal performance improvements of finetuned models

    Fundamentally, the FinetuningScheduler callback enables multi-phase, scheduled finetuning of foundational models.
    Gradual unfreezing (i.e. thawing) can help maximize foundational model knowledge retention while allowing (typically
    upper layers of) the model to optimally adapt to new tasks during transfer learning.

    FinetuningScheduler orchestrates the gradual unfreezing of models via a finetuning schedule that is either implicitly
    generated (the default) or explicitly provided by the user (more computationally efficient). Finetuning phase
    transitions are driven by FTSEarlyStopping criteria (a multi-phase extension of EarlyStopping), user-specified epoch
    transitions or a composition of the two (the default mode). A FinetuningScheduler training session completes when the
    final phase of the schedule has its stopping criteria met.

    Documentation
    -------------
    - https://finetuning-scheduler.readthedocs.io/en/stable/
    - https://finetuning-scheduler.readthedocs.io/en/0.1.2/

extra:
  recipe-maintainers:
    - speediedan
